### users list
GET http://localhost:4000/users
Authorization: Basic kin:test

### users list cloud
GET http://node-euro-2021.appspot.com/users
Authorization: Basic test:test


### delete user by id
DELETE http://node-euro-2021.appspot.com/users/5eaf1722ef24df0df4e92005
Authorization: Basic test:test


### add user
POST http://localhost:4000/users
Authorization: Basic kin:test
Content-Type: application/json

{
"username":"yana",
"password":"test",
"firstName": "firstName1",
"lastName": "lastName1",
"isAdmin": false
}

### auth correct
POST http://localhost:4000/users/authenticate
Content-Type: application/json

{"username":"kin","password":"test"}


### auth correct cloud
POST http://node-euro-2021.appspot.com/users/authenticate
Content-Type: application/json

{"username":"test","password":"test"}


### auth incorrect
POST http://localhost:4000/users/authenticate
Content-Type: application/json

{"username":"kin","password":"test111111"}

### get user by id
GET http://localhost:4000/users/5e6a5272e12b5e37a8628d28
Authorization: Basic kin:test

### update user by id
PUT http://localhost:4000/users/5e7d99c5997f6c1e3061a7ba
Authorization: Basic kin:test
Content-Type: application/json

{
"username":"kin1",
"password":"test",
"firstName": "firDDstName1",
"lastName": "lasDFtName1",
"isAdmin": false
}

### delete user by id
DELETE http://localhost:4000/users/5e6b3be16589823390428a57
Authorization: Basic kin:test


### delete all users
DELETE http://localhost:4000/users
Authorization: Basic kin:test


### get user's stakes by id 
GET http://localhost:4000/users/5eaf037815ddc728dc670fbc/stakes/
Authorization: Basic kin:test

### update user stakes by id 
PUT http://localhost:4000/users/5eaf037815ddc728dc670fbc/stakes/3
Authorization: Basic kin:test
Content-Type: application/json

{  
    "home": 6, 
    "away": 1
}